---
title: "Netzwerk Christiane F - Buch 1&2 WS19/20"
output: html_notebook
---

```{r Pakete laden, Datensatz einlesen und Erstellung igraph Objekt }

# Codebuch für den Datensatz:

library("igraph")
library(igraphdata)

# Einlesen der Edge- und Nodelist
# Datensatz unter: https://github.com/pj015/NetzwerkCF

edges <- read.csv("https://raw.githubusercontent.com/pj015/NetzwerkCF/master/Finale-Edgelist.csv", header=T, as.is=T, sep = ",")
nodes <- read.csv("https://raw.githubusercontent.com/pj015/NetzwerkCF/master/Finale-Nodelist.csv" ,header=T, as.is=T, sep = "," ) 

# erstellt ein igraph-objekt aus der Fusion von Edge- und Nodelist
edgematrix <-as.matrix(edges)

cf <- graph_from_data_frame(d=edgematrix,vertices=nodes,directed = FALSE)
# das igraph-Objekt heisst jetzt "cf" (für das Netzwerk Christiane F. ) und ist ein gerichtetes Netzwerk.

```

```{r Einfache Visualisierung }
# Einfache Visualisierung
plot(cf, layout = layout_with_kk,
     edge.arrow.size=0.5, 
     edge.curved=0.5, 
     main = "Christiane F - Buch 1&2")


# Visualisierung, das Netzwerk entzerren, das Layout verschönern - coords behalten 

durchmesser <- layout.kamada.kawai(cf)
durchmesser <- norm_coords(durchmesser, ymin=-1, ymax=1, xmin=-1, xmax=1)

plot(cf, layout=durchmesser*18.0, rescale=FALSE, ylim=c(-10.0,10.0),xlim=c(-10.0,10.0),asp=0)

```

```{r Visualierung nach Vertex-Attributen für alle Netzwerke}

edge.attributes(cf)$beziehung
edge.attributes(cf)$beziehung2


list.vertex.attributes(cf)
vertex.attributes(cf)
vertex.attributes(cf)$geschlecht

list.vertex.attributes(cf)
vertex.attributes(cf)
vertex.attributes(cf)$kapitel

V(cf)[(V(cf)$geschlecht==2)]$shape <- "circle"
V(cf)[(V(cf)$geschlecht==1)]$shape <- "square"
V(cf)[(V(cf)$geschlecht==3)]$shape <- "circle"

V(cf)[(V(cf)$zustand==2)]$color <- "lightblue"
V(cf)[(V(cf)$zustand==1)]$color <- "lightpink"
V(cf)[(V(cf)$zustand==3)]$color <- "salmon"
plot(cf, vertex.label=NA, layout=layout_nicely)

```

```{r Drogen für alle aus Buch 1 & 2}

E(cf)[E(cf)$alkohol == 1]$color <- "lightblue"
E(cf)[E(cf)$marihuana == 1]$color <- "turquoise"
E(cf)[E(cf)$sonstige_drogen == 1]$color <- "blue"
E(cf)[E(cf)$kokain == 1]$color <- "darkblue"
E(cf)[E(cf)$heroin == 1]$color <- "grey"

V(cf)[(V(cf)$name=="Christiane F")]$size==80

plot(cf, layout=durchmesser*3, vertex.size=6, edge.width=2, vertex.label=NA)

```

```{r Teilnetzwerk für Drogenbeziehung Buch 1 }

# Zeigt uns die Vertex-Attribute des Unternetzwerks "WKVBZ" an.
cf
b1 <- subgraph.edges(cf, E(cf)[kapitel <= 200])
b1
db1 <- delete_edges(b1, E(b1)[alkohol > "1"])
db1 <- delete_edges(b1, E(b1)[marihuana > "1"])
db1 <- delete_edges(b1, E(b1)[sonstige_drogen > "1"])
db1 <- delete_edges(b1, E(b1)[kokain > "1"])
db1 <- delete_edges(b1, E(b1)[heroin > "1"])
db1

durchmesser <- layout.kamada.kawai(b1)
durchmesser <- norm_coords(durchmesser, ymin=-1, ymax=1, xmin=-0.5, xmax=0.5)

plot(b1, layout=durchmesser*14.0, rescale=FALSE, ylim=c(-8.0,8.0),xlim=c(-8.0,8.0),asp=0, vertex.label=NA)

```

```{r Buch 1 b1 Dorgenfarben zugewiesen}

E(b1)[E(b1)$alkohol == 1]$color <- "lightblue"
E(b1)[E(b1)$marihuana == 1]$color <- "turquoise"
E(b1)[E(b1)$sonstige_drogen == 1]$color <- "blue"
E(b1)[E(b1)$kokain == 1]$color <- "darkblue"
E(b1)[E(b1)$heroin == 1]$color <- "grey"

durchmesser <- layout.kamada.kawai(b1)
durchmesser <- norm_coords(durchmesser, ymin=-1, ymax=1, xmin=-2, xmax=2)

plot(b1, layout=durchmesser*8.0, rescale=FALSE, ylim=c(-10.0,10.0),xlim=c(-10.0,10.0),asp=0,
 vertex.size=12, edge.width=2, vertex.label=NA)
```

```{r Alle isolierten Knoten auch Buch 1 Drogennetzwerk löschen}
# Es sollen nur Knoten mit Beziehungen übrig bleiben, d.h. alle Knoten mit degree=="0" können gelöscht werden. Dazu müssen vorher die Degrees entsprechend berechnet werden.

b1 
V(b1)$degree <- degree(b1)
vertex.attributes(b1)$degree
db1 <- delete_vertices(b1,V(b1)[degree == "0"])
db1

V(db1)[V(db1)$name == 15]$color <- "grey"
 
plot(db1, layout=layout.kamada.kawai,
     layout=durchmesser*8.0, rescale=FALSE, ylim=c(-10.0,10.0),xlim=c(-10.0,10.0),asp=0,vertex.label=NA,
     main="Drogennetzwerk Buch 1",
     sub="ohne Isolates")


```

```{r Degrees für Buch 1 Dorgennetzwerk vergeben }

# liefert die Anzahl der Kanten, die durch die Knoten gehen.
degree(db1)

# Verteilung der Knoten als Histogram dargestellt
Buch1Degrees <- degree(db1)
     main="Anzahl der Degrees im Drogennetzwerk- Buch 1"
     
```

```{r Knoten mit dem höchsten degree-Wert dauerhaft hervorheben}
# Wir wollen den Knoten mit dem höchsten degree-Wert dauerhaft hervorheben.

# Berechnung indegree
b1_deg <- degree(db1, mode="in")
b1_deg

# Welcher Knoten hat den höchsten Indegree-Wert?
which.max(degree(db1))

# Dauerhafte Markierung des Knoten 15 (Christiane F - Buch 1)
V(db1)[V(db1)$name == 15]$color <- "grey"
plot(db1, 
     layout = layout_with_fr,
     vertex.label=NA, 
     main="Rahmenfarbe für den höchsten Degree hervorgehoben")



```

```{r Indegree-Knotengröße soll dargestellt werden}

# Buch 1, Christiane F durch die Knotengröße hervorheben 

# Indegrees berechnen und bereits auf einer Skala von 0-1 normalisieren
ind <- degree(db1, mode="in", normalized=T)
ind

plot(db1,
     layout=layout_with_kk,
     vertex.label=NA,
     vertex.size=ind*20, #definiert das Verhältnis der Knoten zueinander (ausprobieren!)
     main="Drogennetzwerk - Buch 1")

```

```{r Teilnetzwerk für Buch 1 erstellen }

# Zeigt uns die Vertex-Attribute des Unternetzwerks "WKVBZ" an.
cf
b1 <- subgraph.edges(cf, E(cf)[kapitel <= 200])
b1
edge.attributes(b1)$kapitel

#plot(b1) für Buch 1 

# Auswahl eines Kapitels aus dem Gesamtdatensatz Christiane F (cf) von Buch 1&2
k1 <- subgraph.edges(cf, E(cf)[kapitel == "101"])
k1
plot(k1)

k2 <- subgraph.edges(cf, E(cf)[kapitel == "102"])
k2
plot(k2)

k3 <- subgraph.edges(cf, E(cf)[kapitel == "103"])
k3
plot(k3)

k4 <- subgraph.edges(cf, E(cf)[kapitel == "104"])
k4
plot(k4)

k5 <- subgraph.edges(cf, E(cf)[kapitel == "105"])
k5
plot(k5)

k6 <- subgraph.edges(cf, E(cf)[kapitel == "106"])
k6
plot(k6)

k7 <- subgraph.edges(cf, E(cf)[kapitel == "107"])
k7
plot(k7)

k8 <- subgraph.edges(cf, E(cf)[kapitel == "108"])
k8
plot(k8)

b1 <- k1 + k2 + k3 + k4 + k5 + k6 + k7 + k8
b1
plot (b1, layout=layout_with_kk,
      main= "Wir Kinder vom Bahnhof Zoo - Buch 1",
      edge.color = "grey80",
      vertex.color = "lightblue",
      edge.arrow.size =1.3,
      sub= "n=158")
# ACHTUNG - SUB ergänzen!

# So können die Kanten und Knoten angezeigt und gezählt werden (ecount = edges)(vcount = vertices)
ecount(b1)
vcount(b1)
# So sieht man die Gesamtanzahl von Kanten und Knoten
b1

plot(b1, 
     layout=layout_with_fr,
     vertex.label=NA, 
      main="Wir Kinder vom Bahnhof Zoo - Buch 1")

# Visualisierung, das Netzwerk entzerren, das Layout verschönern - coords behalten 

durchmesser <- layout.kamada.kawai(b1)
durchmesser <- norm_coords(durchmesser, ymin=-1, ymax=1, xmin=-1, xmax=1)

plot(b1, layout=durchmesser*18.0, rescale=FALSE, ylim=c(-10.0,10.0),xlim=c(-10.0,10.0),asp=0)
```


```{r}
# Visualisierungsparameter, dass sich die Kanten nicht überlagern.
layouts <- grep("^layout_", ls("package:igraph"), value=TRUE)[-1]

# legt ein Layout fest
layouts <- layouts[!grepl("bipartite|merge|norm|sugiyama|tree", layouts)]

# definiert eine 3x3 Felder Matrix für die Darstellung
par(mfrow=c(3,3), mar=c(1,1,1,1)) 
for (layout in layouts) 
 print(layout)
l <- do.call(layout, list(b1))

# plottet das Netzwerk b1 auf die vorgegebenen Layout-Angaben
plot(b1, edge.arrow.mode=.1, layout=l, main=layout,
    edge.curved=curve_multiple(b1))

# setzt die Darstellung wieder auf eine einzelne Abbildung zurück
par(mfrow=c(1,1), mar=c(0,0,0,1))

```


```{r Drogen für alle aus Buch 1 & 2}

E(cf)[E(cf)$alkohol == 1]$color <- "lightblue"
E(cf)[E(cf)$marihuana == 1]$color <- "turquoise"
E(cf)[E(cf)$sonstige_drogen == 1]$color <- "blue"
E(cf)[E(cf)$kokain == 1]$color <- "darkblue"
E(cf)[E(cf)$heroin == 1]$color <- "grey"

plot(cf, vertex.size=3, edge.width=2, vertex.label=NA)

```

```{r Teilnetzwerk für Drogenbeziehung Buch 2 }

# Zeigt uns die Vertex-Attribute des Unternetzwerks "Mein zweites Leben" an.
cf
b2 <- subgraph.edges(cf, E(cf)[kapitel > 200])
b2
db2 <- delete_edges(b2, E(b2)[alkohol > "1"])
db2 <- delete_edges(b2, E(b2)[marihuana > "1"])
db2 <- delete_edges(b2, E(b2)[sonstige_drogen > "1"])
db2 <- delete_edges(b2, E(b2)[kokain > "1"])
db2 <- delete_edges(b2, E(b2)[heroin > "1"])
db2

```

```{r Buch 2 b2 Dorgenfarben zugewiesen}

E(b2)[E(b2)$alkohol == 1]$color <- "lightblue"
E(b2)[E(b2)$marihuana == 1]$color <- "turquoise"
E(b2)[E(b2)$sonstige_drogen == 1]$color <- "blue"
E(b2)[E(b2)$kokain == 1]$color <- "darkblue"
E(b2)[E(b2)$heroin == 1]$color <- "grey"

plot(b2, vertex.size=3, edge.width=2, vertex.label=NA)
```

```{r Alle isolierten Knoten löschen}
# Es sollen nur Knoten mit Beziehungen übrig bleiben, d.h. alle Knoten mit degree=="0" können gelöscht werden. Dazu müssen vorher die Degrees entsprechend berechnet werden.

b2 
V(b2)$degree <- degree(b2)
vertex.attributes(b2)$degree
db2 <- delete_vertices(b2,V(b2)[degree == "2"])
db2

plot(db2, layout=layout_with_kk,
     vertex.size=3,
     main="Drogennetzwerk Buch 2",
     sub="ohne Isolates")

```

```{r Alle isolierten Knoten löschen}
# Es sollen nur Knoten mit Beziehungen übrig bleiben, d.h. alle Knoten mit degree=="0" können gelöscht werden. Dazu müssen vorher die Degrees entsprechend berechnet werden.

db2 
V(db2)$degree <- degree(db2)
vertex.attributes(db2)$degree
db2_relations <- delete_vertices(db2,V(db2)[degree == "2"])
db2_relations

```
```{r Indegree-Knotengröße soll dargestellt werden Buch 2}
# Wir wollen den Knoten mit dem höchsten degree-Wert dauerhaft hervorheben.

# Berechnung indegree
b2_deg <- degree(db2_relations, mode="in")
b2_deg

# Welcher Knoten hat den höchsten Indegree-Wert?
which.max(degree(db2_relations))

# Dauerhafte Markierung des Knoten 15 (Christiane F - Buch 2)
V(db2_relations)[V(db2_relations)$name == 21]$color <- "grey"
plot(db2_relations, 
     layout = layout_with_fr,
     vertex.label=NA, 
     vertex.size=3,
     main="Rahmenfarbe für den höchsten Degree hervorgehoben")
```

```{r Indegree-Knotengröße soll dargestellt werden}

# Buch 2, Christiane F durch die Knotengröße hervorheben 

# Indegrees berechnen und bereits auf einer Skala von 0-1 normalisieren
ind <- degree(db2_relations, mode="in", normalized=T)
ind

plot(db2_relations,
     layout=layout_with_kk,
     vertex.label=NA,
     vertex.size=ind*20, #definiert das Verhältnis der Knoten zueinander (ausprobieren!)
     main="Drogennetzwerk - Buch 2")

```

```{r Teilnetzwerk für Buch 2 erstellen }

 # Zeigt uns die Vertex-Attribute des Unternetzwerks "Mein Zweites Leben - Buch 2" an.
cf
b2 <- subgraph.edges(cf, E(cf)[kapitel > 200])
b2
edge.attributes(b2)$kapitel

#plot(b2) für Buch 2

# Auswahl eines Kapitels aus dem Gesamtdatensatz Christiane F 
b2k1 <- subgraph.edges(cf, E(cf)[kapitel == "201"])
b2k1
plot(b2k1)

b2k2 <- subgraph.edges(cf, E(cf)[kapitel == "202"])
b2k2
plot(b2k2)

b2k3 <- subgraph.edges(cf, E(cf)[kapitel == "203"])
b2k3
plot(b2k3)

b2k4 <- subgraph.edges(cf, E(cf)[kapitel == "204"])
b2k4
plot(b2k4)

b2k5 <- subgraph.edges(cf, E(cf)[kapitel == "205"])
b2k5
plot(b2k5)

b2k6 <- subgraph.edges(cf, E(cf)[kapitel == "206"])
b2k6
plot(b2k6)

b2k7 <- subgraph.edges(cf, E(cf)[kapitel == "207"])
b2k7
plot(b2k7)

b2k8 <- subgraph.edges(cf, E(cf)[kapitel == "208"])
b2k8
plot(b2k8)

b2k9 <- subgraph.edges(cf, E(cf)[kapitel == "209"])
b2k9
plot(b2k9)

b2 <- b2k1 + b2k2 + b2k3 + b2k4 + b2k5 + b2k6 + b2k7 + b2k8 + b2k9
b2

plot (b2k1, layout=layout_with_kk,
      main= "Mein Zweites Leben - Buch 2",
      edge.color = "grey80",
      vertex.color = "lightblue",
      vertex.size=3,
      edge.arrow.size =1.3,
      sub= "n=158")

# ACHTUNG ! SUB erzängen! 

# So können die Kanten und Knoten angezeigt und gezählt werden (ecount = edges)(vcount = vertices)
ecount(b2)
vcount(b2)
# So sieht man die Gesamtanzahl von Kanten und Knoten
b2

# Visualisierung, dass sich die Kanten nicht überschneiden 
plot(b2k1, 
     layout=layout_with_fr,
     vertex.label=NA, 
       vertex.size=3,
      main="Mein Zweites Leben - Buch 2")

# Visualisierungsparameter, dass sich die Kanten nicht überlagern.

layouts <- grep("^layout_", ls("package:igraph"), value=TRUE)[-1]

# legt ein Layout fest
layouts <- layouts[!grepl("bipartite|merge|norm|sugiyama|tree", layouts)]

# Visualisierung, das Netzwerk entzerren, das Layout verschönern - coords behalten 

durchmesser <- layout.kamada.kawai(b2)
durchmesser <- norm_coords(durchmesser, ymin=-1, ymax=1, xmin=-1, xmax=1)

plot(b2k1, vertex.size=3,layout=durchmesser*12.0, rescale=FALSE, ylim=c(-8.0,8.0),xlim=c(-8.0,8.0),asp=0)

# definiert eine 3x3 Felder Matrix für die Darstellung
par(mfrow=c(3,3), mar=c(1,1,1,1)) 
for (layout in layouts) 
 print(layout)
l <- do.call(layout, list(b2))

# setzt die Darstellung wieder auf eine einzelne Abbildung zurück
par(mfrow=c(1,1), mar=c(0,0,0,1))
```


```{r für alle Gefühlsbeziehungen aus buch 1 & 2}

E(cf)[E(cf)$beziehung == 1]$color <- "lightblue"
E(cf)[E(cf)$ beziehung == 2]$color <- "turquoise"
E(cf)[E(cf)$ beziehung == 3]$color <- "blue"
E(cf)[E(cf)$ beziehung == 4]$color <- "darkblue"
E(cf)[E(cf)$ beziehung == 5]$color <- "grey"
E(cf)[E(cf)$ beziehung == 6]$color <- "black"
E(cf)[E(cf)$ beziehung == 7]$color <- "lightpink"
E(cf)[E(cf)$ beziehung == 8]$color <- "pink"
E(cf)[E(cf)$ beziehung == 9]$color <- "red"
E(cf)[E(cf)$ beziehung == 10]$color <- "darkred"
E(cf)[E(cf)$ beziehung == 11]$color <- "yellow"

E(cf)[E(cf)$ beziehung2 == 1]$color <- "lightblue"
E(cf)[E(cf)$ beziehung2 == 2]$color <- "turquoise"
E(cf)[E(cf)$ beziehung2 == 3]$color <- "blue"
E(cf)[E(cf)$ beziehung2 == 4]$color <- "darkblue"
E(cf)[E(cf)$ beziehung2 == 5]$color <- "grey"
E(cf)[E(cf)$ beziehung2 == 6]$color <- "black"
E(cf)[E(cf)$ beziehung2 == 7]$color <- "lightpink"
E(cf)[E(cf)$ beziehung2 == 8]$color <- "pink"
E(cf)[E(cf)$ beziehung2 == 9]$color <- "red"
E(cf)[E(cf)$ beziehung2 == 10]$color <- "darkred"
E(cf)[E(cf)$ beziehung2 == 11]$color <- "yellow"

# Visualisierungsparameter, dass sich die Kanten nicht überlagern.
layouts <- grep("^layout_", ls("package:igraph"), value=TRUE)[-1]

plot(cf, vertex.size=6, edge.width=2, vertex.label=NA)

durchmesser <- layout.kamada.kawai(cf)
durchmesser <- norm_coords(durchmesser, ymin=-1, ymax=1, xmin=-1, xmax=1)

plot(cf, layout=durchmesser*18.0, rescale=FALSE, ylim=c(-10.0,10.0),xlim=c(-10.0,10.0),asp=0, vertex.label=NA)

```

```{r Teilnetzwerk für die Gefühlsbeziehungen}

beb1 <- subgraph.edges(cf, E(cf)[kapitel < 200])
beb1

durchmesser <- layout.kamada.kawai(beb1)
durchmesser <- norm_coords(durchmesser, ymin=-0.5, ymax=0.5, xmin=-0.5, xmax=0.5)

plot(beb1, vertex.label=NA, vertex.size=15 ,layout=durchmesser*14.0, rescale=FALSE, ylim=c(-8.0,8.0),xlim=c(-8.0,8.0),asp=0)
plot(beb1)

```

```{r}
beb2 <- subgraph.edges(cf, E(cf)[kapitel > 108])
beb2

durchmesser <- layout.kamada.kawai(beb1)
durchmesser <- norm_coords(durchmesser, ymin=-0.5, ymax=0.5, xmin=-0.5, xmax=0.5)

plot(beb2, vertex.label=NA, vertex.size=15 ,layout=durchmesser*14.0, rescale=FALSE, ylim=c(-8.0,8.0),xlim=c(-8.0,8.0),asp=0)
plot(beb2)
```

